final_workflow

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -14,24 +14,45 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4.1.7
+        uses: actions/checkout@v4
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '20'
 
-      - name: Docker Build
-        uses: docker/setup-buildx-action@v3.3.0
+      #For Advanced Docker Build Capabilities
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
 
       - name: Log in to Docker Hub
-        uses: docker/login-action@v3.2.0
+        uses: docker/login-action@v3
         with:
           registry: https://index.docker.io/v1/
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
+      - name: Build Docker image
+        id: build
+        run: |
+          docker build -t laravel_app:latest .
+          docker save laravel_app:latest -o vuln-image.tar
+
+      - name: Run Trivy vulnerability scanner in tarball mode
+        uses: aquasecurity/trivy-action@0.20.0
+        id: trivy
+        with:
+          input: vuln-image.tar
+          severity: 'CRITICAL,HIGH'
+
+      - name: Check Trivy scan result
+        if: steps.trivy.outputs.exit-code != 0
+        run: |
+          echo "Trivy scan failed with CRITICAL or HIGH vulnerabilities."
+          exit 1
+
       - name: Build and push Docker image
+        if: steps.trivy.outputs.exit-code == 0
         uses: docker/build-push-action@v4
         with:
           context: .
